### ISSUE TITLE
does not shut down at exit (v79)

### ISSUE THREAD

**Issue by monica80** [jimmejardine/qiqqa-open-source#112]
[Qiqqa20191017-did-not-shut-down.log](https://github.com/jimmejardine/qiqqa-open-source/files/3740600/Qiqqa20191017-did-not-shut-down.log)

When I exit Qiqqa v79, it appears to shut down but it keeps running in the background. I have to use Task Manager to manually End Task. Then I can restart Qiqqa. Attached the last bit of the qiqqa log, in case that's helpful. 

Any help will be appreciated. (note: previously posted on the qiqqa help forum)

**Comment by GerHobbelt** [comment]
Thanks for reporting this issue and the included log file! 👍 

(Related issues/cause of issue: #10, #11, #13 )

This is a known problem with Qiqqa v79. Most often the culprit is a PDF document in one of your libraries which triggers the issue. 

The bad news is it's pretty tough to find out which one it is (some times there's even more than one) and besides, that PDF was downloaded/imported *for a reason* so removing it from the library is not really an option unless the PDF itself is corrupted (can happen during download, while working in the Sniffer, but there are also completely valid PDFs out there which will b0rk v79).

**The good news is work is being done on a new Qiqqa release which should not exhibit this problem**, but there are still a few issues there which I need to resolve involving some of the new features (#82), before this new version is sufficiently usable.

When you feel a little adventurous:

There's an experimental prerelease (v82pre3) available at https://github.com/GerHobbelt/qiqqa-open-source/releases which should resolve this issue, but that release has a UX issue (#82) which can be circumvented if you know what to do precisely or when BibTeX editing in the Qiqqa Sniffer is not important for your workflow.

> The GerHobbelt repo is where the experimental stuff is published; more solid beta/final 
> releases will be released at https://github.com/jimmejardine/qiqqa-open-source/releases
> but those will take quite a while longer to show up as Qiqqa is going through a bit of an overhaul.

IFF you decide to install v82pre3, do note that:

- you should **sync** your Qiqqa Web Libraries before upgrading from v79: only Commercial Qiqqa releases (up to v79) are able to sync the web libraries with the Qiqqa Cloud, i.e. your Qiqqa account at http://www.qiqqa.com/Libraries

  This sync-before-upgrading ensures (if you collaborate on a Qiqqa library) that your local copy of these Qiqqa Library/libraries is up to date. No need to sync when you know you already have the latest in Qiqqa on your local machine.

- Qiqqa Open Source will find these local copies of the Web Libraries and auto-name them as `Legacy WebLibrary - {cryptic GUID code}` -- unfortunately Qiqqa Open Source does not name them like you have been used to with Commercial Qiqqa.

  While Qiqqa Open Source will not be able to *sync* such a library to the Qiqqa Cloud, you can continue working on it locally. 

  When you *downgrade* from v82 to v79 you can resync the library as v82 and v79 are binary compatible in their library formats, so that might serve as a temporary work-around when you collaborate on a Qiqqa Web/Cloud Library.

- as mentioned at the v82pre3 install page on the github site, if you don't like it, you can always downgrade again afterwards to v79 by downloading that installer and installing it as usual: the v79 installer will report v82 as being "older" and then perform an "upgrade", which will re-install v79 on your machine.

**Comment by GerHobbelt** [comment]
Should be fixed as per today (marker commit: 95dff9bc16234ecde02a9e5b0ec8e8223675bda2), will be available in upcoming pre-release v82pre4. (That release will take a few more days as there's still the PDF OCR rescan issue by way of https://github.com/jimmejardine/qiqqa-open-source/issues/95. I hope to have it done by the end of the weekend.)

**Comment by GerHobbelt** [comment]
@monica80: I just put a new prerelease online: v82pre4 at https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7213.27662

You might want to check that one out as it should fix your exiting-Qiiqa problem *and* has a BibTeX editor in the Qiqqa Sniffer that is usable (contrary to v82pre3, which was rather hairy to use there; see https://github.com/jimmejardine/qiqqa-open-source/issues/82).

Please let me know how it works out for you. Cheers.

**Comment by monica80** [comment]
@GerHobbelt : I installed the v82pre4 (and ran Expedition, as recommended). This has solved my problem of qiqqa not shutting down at exit. Yeah! Qiqqa exits and fully ends.  I haven't had a chance to test all aspects of v82pre4 but so far basic functions work. Thanks again!

**Comment by GerHobbelt** [comment]
👍 

If there's anything else, don't hesitate to report as an issue here.

(BTW: v82pre5 prerelease is available at https://github.com/GerHobbelt/qiqqa-open-source/releases ; not a lot of change, but should be a bit more stable than pre4 and fixes one UI bug where a side panel did not resize)
