### ISSUE TITLE
Migrating from commercial Qiqqa in winXP virtualbox to OS Qiqqa in win10 in vb: tips?

### ISSUE THREAD

**Issue by SimonDedman** [jimmejardine/qiqqa-open-source#150]
Hi folks, thanks for taking on this laudable project.
I've been without QIqqa for a while but need to get back to it. My previous setup was commercial Qiqqa on winXP in a virtualbox on a linux laptop, with papers in /Dropbox/Papers/ which also creates the library structure elsewhere on the laptop itself. /Papers is 4gb. I'd love for the library to be stored in the cloud but I'm not sure it's possible to have the originals (kept in logical subject subfolders) in the cloud and synced only, without all of the PDFs being duplicated elsewhere?

If someone could advise the best strategy to migrate from my existing setup, with the backup file, into a new one, that would be very much appreciated. It would be great to be able to use Qiqqa on both machines but I suspect that won't be possible insofar as OS Qiqqa won't work on XP so I'll have to stay with the commercial install on the laptop... which probably won't sync library with OS Qiqqa??

Cheers!

**Comment by SimonDedman** [comment]
Converting to intranet library worked great, syncing now in two machines, only issue now is whether it's possible to intranet sync to old version original qiqqa on Windows xp, it looks like intranet library is new in the foss version?

**Comment by GerHobbelt** [comment]
The IntraNet Library type was (AFAICT) a library type which existed in commercial Qiqqa as well, but was only available for folks which purchased one of the (higher) paid packages. It's too long ago that I looked at commercial Qiqqa feature sets so I may be wrong.

🤔 Git: commit 4ad8e5f0619827563a28e5bd2b6323910f722ed0 : open source version is now able to 'see' the legacy web libraries. Cannot dig up a commit which "introduced" Intranet libraries per se...

---

Syncing to an older Qiqqa version *may* be a bit of a bother, as both versions will not be "thinking" *exactly* the same way: while FOSS Qiqqa v80 (and above) are database-compatible with the last commercial Qiqqa (v79), the commercial Qiqqa will have different sync behaviour for "Web Libraries" (now marked as "Legacy Libraries") than FOSS Qiqqa, simply because FOSS Qiqqa does not have access to the (obsoleted) Qiqqa Cloud a.k.a. Web Libraries' cloud store owned by Quantisle: that code was taken out before Qiqqa was made Open Source.

Possibly relevant technical bits & pieces:

- https://github.com/jimmejardine/qiqqa-open-source/issues/142#issuecomment-563500989-permalink (Qiqqa can grab documents off a Dropbox share, but sharing/syncing onto a Dropbox share is still a bit risky; see also #77 )
- https://github.com/jimmejardine/qiqqa-open-source/issues/77
- https://github.com/jimmejardine/qiqqa-open-source/issues/76
- https://github.com/jimmejardine/qiqqa-open-source/issues/75
- https://github.com/jimmejardine/qiqqa-open-source/issues/4

---

🤔 Hm, I hope I didn't confuse matters. Ignore if feels like cognitive dissonance. 🤔

**Comment by SimonDedman** [comment]
Sorry for the slow reply. Finally got around to trying to this, adding an intranet library which is already synced through a NAS, to a commercial qiqqa v79 install on winXP. The setup works as normal but sync options are greyed out and it subsequentl can't begin the sync thus it's not a viable option. Not the end of the world for me as I still have the old library and won't be using it much/at all, but I figured I'd share my findings for others.
Cheers!

**Comment by GerHobbelt** [comment]
If I understand you correctly, then you have a synced copy of the old Web library locally and then Open source qiqqa has 'sync' greyed out?

If so, that would be expected, as OSS Qiqqa does not know & is unable to sync with Qiqqa cloud storage (no means to access that web service).

So there's a few bits here:

- anyone with a Web Library needs to make sure their **local copy** is up-to-date by synchronization with the Qiqqa Cloud Storage by using Commercial Qiqqa v79.

- then, having an up-to-date **local copy** of that Web Library, you can continue to use it **locally** like any other Qiqqa library, using Open source Qiqqa. 

  Qiqqa Open Source will discover such (and other) libraries and list them in the library overview panel (though the name might be an unexpected UUID, rather than the human-readable name you gave that library back then).

  (TODO note @GerHobbelt: write a note about Qiqqa library discovery and how it works + what it expects)

- 'sync' will be greyed out = disabled as OSS Qiqqa is not able to sync with Qiqqa Cloud Storage, hence doesn't know *jow to sync* and therefor turns sync *off*.

- what a **future Qiqqa should be doing** is offer up a choice to the user to *change* where to sync a library to. Such a library can then be pointed at a DropBox / GoogleDrive / Whatchammacallit directory and sync should then be able to commence. 

  Regrettably, this has not yet been built into v82.

---

BTW: If I misunderstood your findings, please correct me. Thanks for reporting!

**Comment by GerHobbelt** [comment]
And apologies for my very late reply!

**Comment by SimonDedman** [comment]
Updating this: Qiqqa in win10 in dual boots (2 machines with same config), original files directory in dropbox folder on the linux partition, QiqqaSync directory in a NAS-sync folder on the linux partition. In Windows, map NAS as network drive, set watch folder as the directory in dropbox (which is synced to NAS, so this is in the nas sync folder), and point intranet library to NAS folder.

All sorted, working great on the first machine. Issues on the other one but I'll open a separate post. Cheers!
