### ISSUE TITLE
Bug: The GUI has two buttons for going to Google Scholar (redundancy)

### ISSUE THREAD

**Issue by raindropsfromsky** [jimmejardine/qiqqa-open-source#188]
![image](https://user-images.githubusercontent.com/9047168/77643652-c4b8cb80-6f85-11ea-83c9-295e0fe00b39.png)

The strip has one button called **Online databases**, which lists **Google Scholar** as an option.
And then it has a separate stand-alone button for **Google Scholar**.

The latter is redundant: It can be removed without any loss of clarity or functionality.
(Occam's razor)

**Comment by GerHobbelt** [comment]
Heh. That one wasn't even an issue before v82pre8 as the entire side panel was hidden. 😄 

Anyway, both are quite different: the top one is a list of search engines where you go to in a sniffer like fashion, looking for related material.

The bottom one is a pre-fetched list of Google Scholar suggestions, which were obtained by Qiqqa in the background while your document view was opened.

So in a sense the results would be the same in the end, but the top is "here can you go if you want to look for something" while the bottom one is "here's some prepared hints/subjects for you to peruse in Scholar if you like"

Alas, not the cleanest UI and I'd rather get rid completely of that implicit Google Search query that sources the bottom one as Google Scholar has become very finicky these days, largely in order to stave off crawlers and other entities that are not interested nor inclined in clicking on advertisements :wink:  Related matter: #155

**Comment by GerHobbelt** [comment]
Addressed indirectly by the new addition of the (default state: OFF) GoogleScholar_DoExtraBackgroundQueries configuration option feature in the new prerelease https://github.com/GerHobbelt/qiqqa-open-source/releases/tag/v82.0.7555-31312.

Relevant commits: SHA-1: 42fab986a6ba2bf73c8061609d8c328408fa95c0 & SHA-1: cfbc9c3423416dcbe43640a5c5ccdc06d987ab35 which remove the background google Scrape and the results thereof displayed in the 'Google Scholar' tab in the sidebar.

End result: redundancy in the UI is reduced alongside. 😄 

P.S.: Thanks for our discussions in the past; I hope you'll stick around. 😉
