### ISSUE TITLE
Google group not public

### ISSUE THREAD

**Issue by mahfiaz** [jimmejardine/qiqqa-open-source#207]
According to Readme.md I tried to join the google group, but could not.
On page https://groups.google.com/forum/#!forum/qiqqa-releases
there is an error:
"This group either doesn't exist, or you don't have permission to access it. If you're sure this group exists, contact the owner of the group and ask them to give you access."

**Comment by GerHobbelt** [comment]
Odd. 😕  I checked the settings and they look all right, as in: the group should be world-visible:

![Annotation 2020-04-27 135233](https://user-images.githubusercontent.com/402462/80369683-f5469a80-888e-11ea-94c6-93165d144c64.png)

I also checked how it looks when I'm not logged into Google: then I see at least this:

![Annotation 2020-04-27 135813](https://user-images.githubusercontent.com/402462/80369813-2cb54700-888f-11ea-9568-d240a8da6db9.png)

Ok, it's Dutch then (because Google assumes defaults based on GeoIP, which *is* NL). The only odd/wrong thing being them displaying a red 'Post Message' button, which isn't entirely as intended -- I'd expected a 'Join' button there as only admins are allowed to post ATM.

Given that, I think I should point at this link for a *slightly* better UX there:

https://support.google.com/groups/answer/1067205?hl=en

**Comment by GerHobbelt** [comment]
\<off-topic>

> Given that, I think I should point at this link for a slightly better UX there:
>
> https://support.google.com/groups/answer/1067205?hl=en

Adjusted the Welcome Message, which is world-visible.

\</off-topic>

**Comment by GerHobbelt** [comment]
Could you please retry and see what goes wrong, when you follow Google's guideline at https://support.google.com/groups/answer/1067205?hl=en ?

**Comment by mahfiaz** [comment]
Today everything worked just as expected. No idea what went wrong before. Thanks!
