### ISSUE TITLE
Installing v82

### ISSUE THREAD

**Issue by gidleydevon** [jimmejardine/qiqqa-open-source#228]
I'm not a coder just a regular user and I'm having the hardest time getting the most recent version, and navigating all of the files, etc. Can someone provide simple instructions to update my Qiqqa? I downloaded qiqqa-open-source-82.0.7357.40407 and can't see how to install anything... I have managed to download v80 but it keeps freezing when I try to open PDFs so I was hoping the update would be improved. 
Thanks

**Comment by GerHobbelt** [comment]
Wrote https://github.com/jimmejardine/qiqqa-open-source/blob/master/docs-src/FAQ/Installing%20Qiqqa%20-%20Updating%20Qiqqa.md today. Hope that one helps you with the download & install process.

Re PDF freezing: it depends, as v82 still uses the same old PDF render engine, etc. as v80, so you MAY end up with a couple of blank pages, but most crashes or lockups should be fixed. At least the ones I encountered with my own (quite large) library and PDFs which were corrupted during download.

## If you have any PDF where v82 locks up, crashes or otherwise acts up / behave unexpectedly, I am VERY INTERESTED in a copy of that PDF!

(https://github.com/GerHobbelt/Evil-PDF-Library-for-Qiqqa is where I collect all such nastiness. 😄)

**Comment by gidleydevon** [comment]
Thank you so much for producing the document - I never would have found the update otherwise. Following your instructions I got it installed no problem. I will keep an eye out for PDFs with issues and share them if/when I discover them. Thanks again this made a big difference!

**Comment by itsahmedkhan** [comment]
Hy @GerHobbelt Thanks alot for this.

**Comment by GerHobbelt** [comment]
Related: #282

**Comment by GerHobbelt** [comment]
Closing this one as this is now resolved: README at github front page links to the referenced document.

When this is still an issue for you, please open another issue (and then reference this issue's number there-in, e.g. #282 or #228
