### ISSUE TITLE
search engine in library stop working

### ISSUE THREAD

**Issue by emanelbanna** [jimmejardine/qiqqa-open-source#274]

**Comment by GerHobbelt** [comment]
Which version of qiqqa are you running?

**Comment by artdijk** [comment]
Same problem here, using version 82.0.7579.33985

**Comment by artdijk** [comment]
When reinstalled other v82 the functionality is not recovered.
I'm afraid this is a very annoying bug...

**Comment by GerHobbelt** [comment]
🤔   What you might want to try is kill the search index / re-index the library.

**Re-indexing** is done via Qiqqa > Home > Tools > Qiqqa Configuration:

![image](https://user-images.githubusercontent.com/402462/103279349-dd02be80-49cd-11eb-823d-132a59a395c4.png)

Then scroll down to bottom till you see these:

![image](https://user-images.githubusercontent.com/402462/103279410-fd327d80-49cd-11eb-93cd-be4a6d870f82.png)

and click the "Rebuild library search indexes".

---

---

If that didn't work for you (YMMV), then we'll have to dig further into the issue and see what is making it misbehave: I've seen non-working search indexes in the past (v79 & v80) but not been able to pinpoint *exactly* what's going wrong in the LuceneNET search engine used by Qiqqa every time -- Qiqqa does use an old version (#23) and several problems which led to this behaviour have been fixed in the past (#20, #17, #16, #13). 

Given that you're running latest v82 pre-release means there's still trouble lurking somewhere inside. 😞

**Comment by GerHobbelt** [comment]
@emanelbanna @artdijk - if the above doesn't work for you (the re-indexing), then I'll need to have a look at the Qiqqa log files to see if anything pops out in the there as a hint to me what might be going wrong with your particular search indexes.

See #264 comments for a guide how the collect and zip/bundle the logfiles. Email them to ger at hobbelt.com with a subject line referencing Qiqqa and this issue number to help the spam filters make the correct choice. 😉

**Comment by artdijk** [comment]
Thanks Ger, the reindex seemed to work, although I expect some more search hits that the results shown. Is the reindex a long process for 2500 publication (about 220 000) pages ?

**Comment by GerHobbelt** [comment]
Yup, re-indexing can take a while. Might be handy to let Qiqqa run for
several hours wheen you're not actively using it as the re-indexing happens
in the background.

Met vriendelijke groeten / Best regards,

Ger Hobbelt

--------------------------------------------------
web:    http://www.hobbelt.com/
        http://www.hebbut.net/
mail:   ger@hobbelt.com
mobile: +31-6-11 120 978
--------------------------------------------------

**Comment by GerHobbelt** [comment]
Closing this one. If the problem recurs, please open a new issue. Thanks!
