### ISSUE TITLE
Qiqqa does not work on Microsoft 2016

### ISSUE THREAD

**Issue by Keith19-jkl** [jimmejardine/qiqqa-open-source#302]
Whenever I try to cite, it always says that Microsoft word is not running.

**Comment by Keith19-jkl** [comment]
Hi guys, on a second thought, is there a microsoft registry for microsoft office 2016? 
Last time I checked, there wasn't any. Only for older versions. (2003,2007,2013,XP, before XP)

**Comment by GerHobbelt** [comment]
You mean a Windows Registry entry which is set when Office2016 is installed, i.e. a way to detect if MSOffice is installed on the machine and where it has been installed?

**Comment by Keith19-jkl** [comment]
Yes that is what I am looking for. Do you know where it is? Thank you

**Comment by GerHobbelt** [comment]
Had to look it up. Got this: https://docs.microsoft.com/en-US/office/troubleshoot/word/reset-options-and-settings-in-word

Meanwhile, Qiqqa connects to MSWord via COM interface:

```csharp
GetActiveObject("Word.Application")
```

If I google that one with trouble to connect, this one pops up: https://support.microsoft.com/en-us/topic/getobject-or-getactiveobject-cannot-find-a-running-office-application-6cdf21a3-ac90-512b-6bff-badc5f4cc215

Also note this one: https://kbarik.wordpress.com/2020/01/17/automate-ms-office-applications-using-python-win32com-module/ which discusses stuff with python instead of C#, but this smells like it might describe your problem: that MSWord focus bug vs the "registering in the ROT". Anyway, might be worth a try to look into that.

**Comment by Keith19-jkl** [comment]
I got it. Thank you

**Comment by GerHobbelt** [comment]
👍 

Has your issue been solved?

**Comment by Keith19-jkl** [comment]
Hi there. Sorry for late reply. In my opinion, I think I might reinstall the Microsoft Office 2016.

**Comment by GerHobbelt** [comment]
Closing this one for now. If you have trouble with Qiqqa again, please file a new issue. Thanks!
