### ISSUE TITLE
@jimme: DropBox detection: what went wrong that we needed it?

### ISSUE THREAD

**Issue by GerHobbelt** [jimmejardine/qiqqa-open-source#77]
@jimmejardine : Qiqqa has DropBox protection built in for Qiqqa base path, which I can understand (running any database on top of sharable storage with potentially multiple accessors is a nightmare), but Qiqqa can **sync** to a OneDrive/GoogleDrive/DropBox/WhatHaveYouInDaCloud URI without trouble, right? (no database activity involved, just [many] file copying)

(Or it's me and my occasional cognitive dissonance kicking in at https://getsatisfaction.com/qiqqa/topics/library-in-dropbox-or-cloud )

Just a quick yes/no question.

**Comment by jimmejardine** [comment]
the qiqqa core databases can't be on a shared drive so the databases corrupt. hence the warming mechanism.

but in the open source version of qiqqa, you can create a library on a shared folder (dropbox, googledrive, etc), and then sync to that, so that your other computers or other people you have permissioned (in dropbox/googledrive/etc) can sync down the changes

the sync mechanism for dropbox is fairly rudimentary (i quickly retrofitted it so that i could opensource qiqqa).  the first person to 'touch' a file, wins it.  any later collissions on that file by others with having synced first are lost...

**Comment by GerHobbelt** [comment]
As I thought. (Didn't know about the retrofit, but some bits of the codebase smelled like quick kill-and-edit action to me. The retrofit explains that.)

:+1:
